name: LSA Live Scraper

on:
  schedule:
    # Her 5 dakikada bir otomatik çalışır
    - cron: '*/10 * * * *'
  workflow_dispatch: # Elle tetikleme butonu

# Duyurudaki gibi Node24 zorlamasını aktif edip uyarıyı kapatıyoruz
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v4.2.0

      - name: Node.js Kur
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '24' # Doğrudan Node 24 kullanıyoruz

      - name: Paketleri Yükle
        run: npm install

      - name: Botu Çalıştır
        env:
          GOOGLE_COOKIES: ${{ secrets.GOOGLE_COOKIES }}
        run: node scraper.js
